/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUİ;
import FileProcess.ExtractSourceFiles;
import FileProcess.FileEngine;
import FileProcess.MakeTxtFiles;
import FileProcess.MemberInformaion;
import FileProcess.SourceListAndTargetListİmplementaion;
import FileProcess.WriteResults;
import javax.swing.JOptionPane;

/**
 *
 * @author aliemre
 */
public class RegisterAndSignInFrame extends javax.swing.JFrame {

    private    FileEngine fileEngine;
        
        
    public RegisterAndSignInFrame() {
        initComponents();
        fileEngine= new FileEngine(new ExtractSourceFiles()  ,new MakeTxtFiles() ,
                new MemberInformaion(), new SourceListAndTargetListİmplementaion(), new WriteResults());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralFramejPanel = new javax.swing.JPanel();
        ChooseOptionjTabbedPane = new javax.swing.JTabbedPane();
        RegisterjPanel = new javax.swing.JPanel();
        jLabelRegisterPassword2 = new javax.swing.JLabel();
        jLabelRegisterNickname = new javax.swing.JLabel();
        jLabelRegisterPassword1 = new javax.swing.JLabel();
        jTextFieldRegisterNickname = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jPasswordFieldRegister = new javax.swing.JPasswordField();
        jPasswordFieldRegisterCheck = new javax.swing.JPasswordField();
        jButtonMainMenu = new javax.swing.JButton();
        jLabelRegisterEmail = new javax.swing.JLabel();
        jTextFieldRegisterEmail = new javax.swing.JTextField();
        SignInjPanel = new javax.swing.JPanel();
        jLabelSignInNickname1 = new javax.swing.JLabel();
        jLabelSignInPassword1 = new javax.swing.JLabel();
        jTextFieldSignInNickname = new javax.swing.JTextField();
        jTextFieldSignInPassword = new javax.swing.JPasswordField();
        LoginjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GeneralFramejPanel.setBackground(new java.awt.Color(255, 51, 102));
        GeneralFramejPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChooseOptionjTabbedPane.setBackground(new java.awt.Color(102, 51, 255));

        RegisterjPanel.setBackground(new java.awt.Color(255, 0, 102));
        RegisterjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegisterjPanel.setFont(new java.awt.Font("Hiragino Sans", 1, 13)); // NOI18N

        jLabelRegisterPassword2.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterPassword2.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword2.setText("Password Again:");

        jLabelRegisterNickname.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterNickname.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterNickname.setText("Nickname:");

        jLabelRegisterPassword1.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterPassword1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword1.setText("Password:");

        jTextFieldRegisterNickname.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldRegisterNickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldRegisterNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldRegisterNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterNicknameActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(255, 215, 0));
        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(20, 30, 50));
        jButtonRegister.setText("SAVE");
        jButtonRegister.setFocusPainted(false);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jPasswordFieldRegister.setBackground(new java.awt.Color(255, 215, 0));
        jPasswordFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordFieldRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegisterActionPerformed(evt);
            }
        });

        jPasswordFieldRegisterCheck.setBackground(new java.awt.Color(255, 215, 0));
        jPasswordFieldRegisterCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldRegisterCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordFieldRegisterCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegisterCheckActionPerformed(evt);
            }
        });

        jButtonMainMenu.setBackground(new java.awt.Color(255, 204, 0));
        jButtonMainMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMainMenu.setText("EXIT");
        jButtonMainMenu.setFocusPainted(false);
        jButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMenuActionPerformed(evt);
            }
        });

        jLabelRegisterEmail.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterEmail.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterEmail.setText("E-Mail");

        jTextFieldRegisterEmail.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldRegisterEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldRegisterEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldRegisterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterjPanelLayout = new javax.swing.GroupLayout(RegisterjPanel);
        RegisterjPanel.setLayout(RegisterjPanelLayout);
        RegisterjPanelLayout.setHorizontalGroup(
            RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterjPanelLayout.createSequentialGroup()
                        .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterjPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                                .addGap(0, 393, Short.MAX_VALUE)
                                .addComponent(jButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                                .addComponent(jPasswordFieldRegisterCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterjPanelLayout.createSequentialGroup()
                        .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                                .addComponent(jLabelRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                                .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                                .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(258, 258, 258))))
        );
        RegisterjPanelLayout.setVerticalGroup(
            RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterjPanelLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldRegisterCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(RegisterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );

        ChooseOptionjTabbedPane.addTab("Register", RegisterjPanel);

        SignInjPanel.setBackground(new java.awt.Color(102, 204, 0));
        SignInjPanel.setForeground(new java.awt.Color(102, 0, 102));

        jLabelSignInNickname1.setBackground(new java.awt.Color(255, 215, 0));
        jLabelSignInNickname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSignInNickname1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelSignInNickname1.setText("Nickname Or e-mail");

        jLabelSignInPassword1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSignInPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSignInPassword1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelSignInPassword1.setText("Password:");

        jTextFieldSignInNickname.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldSignInNickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSignInNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldSignInNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignInNicknameActionPerformed(evt);
            }
        });

        jTextFieldSignInPassword.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldSignInPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSignInPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldSignInPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignInPasswordActionPerformed(evt);
            }
        });

        LoginjButton.setBackground(new java.awt.Color(255, 0, 153));
        LoginjButton.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        LoginjButton.setText("Login");
        LoginjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignInjPanelLayout = new javax.swing.GroupLayout(SignInjPanel);
        SignInjPanel.setLayout(SignInjPanelLayout);
        SignInjPanelLayout.setHorizontalGroup(
            SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInjPanelLayout.createSequentialGroup()
                .addGroup(SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignInjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSignInNickname1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jLabelSignInPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jTextFieldSignInPassword)))
                    .addGroup(SignInjPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(LoginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        SignInjPanelLayout.setVerticalGroup(
            SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInjPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(SignInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(LoginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        ChooseOptionjTabbedPane.addTab("Sign In", SignInjPanel);

        GeneralFramejPanel.add(ChooseOptionjTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralFramejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralFramejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRegisterNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterNicknameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterNicknameActionPerformed
    
    
    private void resetRegister(){
    jTextFieldRegisterEmail.setText("");
    jTextFieldRegisterNickname.setText("");
    jPasswordFieldRegister.setText("");
    jPasswordFieldRegisterCheck.setText("");
    
    
    }
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String username = jTextFieldRegisterNickname.getText().trim();
        String email = jTextFieldRegisterEmail.getText().trim();

        String password1 = new String(jPasswordFieldRegister.getPassword());
        String password2 = new String(jPasswordFieldRegisterCheck.getPassword());
        
        if(!fileEngine.RegisterProcess(username, password1, password2)){
            JOptionPane.showMessageDialog(this, "kayıt başarısız");
            return ;
        }
        
        String passwordWithHash = password1.hashCode() + "";
        if (!fileEngine.WriteNewMembers(username, passwordWithHash, email)) {
            JOptionPane.showMessageDialog(this, "Kayıt yazılamadı. E-posta adresini ve dosya iznini kontrol edin.");
            return;
        }
        JOptionPane.showMessageDialog(this, "kayıt başarıLI");
        fileEngine.readFileAgain();resetRegister();
        

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jPasswordFieldRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegisterActionPerformed

    private void jButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMenuActionPerformed
        System.exit(0);
        
        
    }//GEN-LAST:event_jButtonMainMenuActionPerformed

    private void jPasswordFieldRegisterCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegisterCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegisterCheckActionPerformed

    private void jTextFieldSignInNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignInNicknameActionPerformed

    }//GEN-LAST:event_jTextFieldSignInNicknameActionPerformed

    private void jTextFieldSignInPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignInPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignInPasswordActionPerformed

    private void LoginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginjButtonActionPerformed
        String username=jTextFieldSignInNickname.getText();
        String password = new String(jTextFieldSignInPassword.getPassword());
        

        password = password.hashCode() + "";
        if(!fileEngine.SignInProcess(username, password)){
            JOptionPane.showMessageDialog(this, " login başarısız");
            return;
        }
        
        JOptionPane.showMessageDialog(this, "kayıt başarılı");
        
        SourceAndTargetProcessFrame frame= new SourceAndTargetProcessFrame(fileEngine);
        frame.setVisible(true); this.setVisible(false);
        




        // TODO add your handling code here:
    }//GEN-LAST:event_LoginjButtonActionPerformed

    private void jTextFieldRegisterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAndSignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAndSignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAndSignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAndSignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAndSignInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ChooseOptionjTabbedPane;
    private javax.swing.JPanel GeneralFramejPanel;
    private javax.swing.JButton LoginjButton;
    private javax.swing.JPanel RegisterjPanel;
    private javax.swing.JPanel SignInjPanel;
    private javax.swing.JButton jButtonMainMenu;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabelRegisterEmail;
    private javax.swing.JLabel jLabelRegisterNickname;
    private javax.swing.JLabel jLabelRegisterPassword1;
    private javax.swing.JLabel jLabelRegisterPassword2;
    private javax.swing.JLabel jLabelSignInNickname1;
    private javax.swing.JLabel jLabelSignInPassword1;
    private javax.swing.JPasswordField jPasswordFieldRegister;
    private javax.swing.JPasswordField jPasswordFieldRegisterCheck;
    private javax.swing.JTextField jTextFieldRegisterEmail;
    private javax.swing.JTextField jTextFieldRegisterNickname;
    private javax.swing.JTextField jTextFieldSignInNickname;
    private javax.swing.JPasswordField jTextFieldSignInPassword;
    // End of variables declaration//GEN-END:variables
}
