/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUİ;

import javax.swing.JOptionPane;
import FileProcess.FileEngine;
import FileProcess.ListValidation;

/**
 *
 * @author aliemre
 */
public class SourceAndTargetProcessFrame extends javax.swing.JFrame {

    /**
     * Creates new form SourceAndTargetProcessFrame
     */
    String sourceListName="";String sourceList="";String targetList="";
    FileEngine fileEngine;
    public SourceAndTargetProcessFrame(FileEngine file) {
        initComponents();
         
        fileEngine=file;
        AddjButton.setVisible(false);
         ChoicejButton.setVisible(false);
         jButtonConfirm.setVisible(false);
        SourceListjTextArea.setVisible(false);
        TargetListjTextArea.setVisible(false);
        jTextFieldSourceListName.setVisible(false);
        jLabelAddOrChoice.setVisible(false);
        jButtonStart.setVisible(false);
        jButtonVerify.setVisible(false);
       LessonNamejLabel.setVisible(false);
       LessonNamejTextField.setVisible(false);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddChoicejButton = new javax.swing.JButton();
        jButtonAddSwitch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SourceListjTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TargetListjTextArea = new javax.swing.JTextArea();
        AddjButton = new javax.swing.JButton();
        ChoicejButton = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jLabelAddOrChoice = new javax.swing.JLabel();
        jTextFieldSourceListName = new javax.swing.JTextField();
        jButtonVerify = new javax.swing.JButton();
        LessonNamejLabel = new javax.swing.JLabel();
        LessonNamejTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddChoicejButton.setText("ADD/CHOICE");
        AddChoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddChoicejButtonActionPerformed(evt);
            }
        });

        jButtonAddSwitch.setText("ADD/SWİTCH");
        jButtonAddSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSwitchActionPerformed(evt);
            }
        });

        SourceListjTextArea.setColumns(20);
        SourceListjTextArea.setRows(5);
        SourceListjTextArea.setText("theee are source list\n");
        jScrollPane1.setViewportView(SourceListjTextArea);

        TargetListjTextArea.setColumns(20);
        TargetListjTextArea.setRows(5);
        TargetListjTextArea.setText("theee are source list");
        jScrollPane2.setViewportView(TargetListjTextArea);

        AddjButton.setText("Add");
        AddjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButtonActionPerformed(evt);
            }
        });

        ChoicejButton.setText("Choice");
        ChoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoicejButtonActionPerformed(evt);
            }
        });

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelAddOrChoice.setText("jLabel1");

        jTextFieldSourceListName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSourceListNameActionPerformed(evt);
            }
        });

        jButtonVerify.setText("Verify");
        jButtonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifyActionPerformed(evt);
            }
        });


        LessonNamejLabel.setText("Lesson's Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(AddChoicejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonVerify))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButtonConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                )
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(AddjButton)
                                        .addGap(65, 65, 65))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelAddOrChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChoicejButton)
                                    .addComponent(jTextFieldSourceListName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57)
                        .addComponent(LessonNamejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LessonNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddChoicejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAddOrChoice)
                                    .addComponent(jTextFieldSourceListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChoicejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        
                                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LessonNamejLabel)
                                    .addComponent(LessonNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButtonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void resetSourceListActions(){
       SourceListjTextArea.setVisible(false);
    AddjButton.setVisible(false); ChoicejButton.setVisible(false);
    jButtonConfirm.setVisible(false);
    jTextFieldSourceListName.setVisible(false);
    jLabelAddOrChoice.setVisible(false);
    }
    private void resetTargetListActions(){
     TargetListjTextArea.setVisible(false);
         jButtonConfirm.setVisible(false);
    
    }
    
    private void AddChoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddChoicejButtonActionPerformed
        try {
    
            JOptionPane.showMessageDialog(this, "please enter student number and name");
                  SourceListjTextArea.setVisible(true);
        AddjButton.setVisible(true); ChoicejButton.setVisible(true);
    
          String sourceLists= fileEngine.sendSourceListsToUser(fileEngine.getterUsername());
           SourceListjTextArea.setText("Theese are your source lists \n"+ sourceLists);
         
            return;
            // TODO add your handling code here:
        } catch (IllegalArgumentException | IllegalStateException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_AddChoicejButtonActionPerformed

    private void jButtonAddSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSwitchActionPerformed
            JOptionPane.showMessageDialog(this, "please enter student number and note");
        TargetListjTextArea.setVisible(true);
        jButtonStart.setVisible(false);
         jButtonVerify.setVisible(true); TargetListjTextArea.setText(""); LessonNamejLabel.setVisible(true);
       LessonNamejTextField.setVisible(true);
         return;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddSwitchActionPerformed

    private void AddjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButtonActionPerformed
        jLabelAddOrChoice.setText("Add SourceList"); jLabelAddOrChoice.setVisible(true);
        ChoicejButton.setVisible(false); jButtonConfirm.setVisible(true);
        jTextFieldSourceListName.setVisible(true);
        SourceListjTextArea.setText("");

                    // TODO add your handling code here:
    }//GEN-LAST:event_AddjButtonActionPerformed

    private void ChoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoicejButtonActionPerformed
        
        jLabelAddOrChoice.setText("Choice SourceList shape truely"); jLabelAddOrChoice.setVisible(true);
        AddjButton.setVisible(false); jButtonConfirm.setVisible(true);
        jTextFieldSourceListName.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_ChoicejButtonActionPerformed

    private void jButtonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifyActionPerformed
        String error = ListValidation.check(TargetListjTextArea.getText(), true);
        if (!error.isEmpty()) {
            jButtonStart.setVisible(false);
            JOptionPane.showMessageDialog(this, error);
            return;
        }
        if (!ListValidation.validName(LessonNamejTextField.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Geçerli bir ders adı girin.");
            return;
        }
        targetList = TargetListjTextArea.getText().strip();
        jButtonStart.setVisible(true);
    }//GEN-LAST:event_jButtonVerifyActionPerformed

    private void jTextFieldSourceListNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSourceListNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSourceListNameActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        try {
            String name = jTextFieldSourceListName.getText().trim();
            if (!ListValidation.validName(name)) {
                JOptionPane.showMessageDialog(this, "Geçerli bir liste adı girin.");
                return;
            }
            String username = fileEngine.getterUsername();
            String selectedSource;
            if (AddjButton.isVisible()) {
                selectedSource = SourceListjTextArea.getText().strip();
                String error = ListValidation.check(selectedSource, false);
                if (!error.isEmpty()) {
                    JOptionPane.showMessageDialog(this, error);
                    return;
                }
                if (!fileEngine.addingSourceList(selectedSource, username, name)) {
                    JOptionPane.showMessageDialog(this, "Liste eklenemedi. Aynı adla bir listeniz olabilir.");
                    return;
                }
            } else {
                selectedSource = fileEngine.choosenList(username, name);
                if (selectedSource.isBlank()) {
                    JOptionPane.showMessageDialog(this, "Bu isimde bir liste bulunamadı.");
                    return;
                }
            }
            sourceList = selectedSource;
            sourceListName = name;
            resetSourceListActions();
            JOptionPane.showMessageDialog(this, "Kaynak liste hazır: " + name);
        } catch (IllegalArgumentException | IllegalStateException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        String error = ListValidation.check(sourceList, false);
        if (error.isEmpty()) {
            error = ListValidation.check(TargetListjTextArea.getText(), true);
        }
        String lessonName = LessonNamejTextField.getText().trim();
        if (error.isEmpty() && !ListValidation.validName(lessonName)) {
            error = "Geçerli bir ders adı girin.";
        }
        if (!error.isEmpty()) {
            JOptionPane.showMessageDialog(this, error);
            return;
        }
        targetList = TargetListjTextArea.getText().strip();
        try {
            WriteAndMakeResultsFrame frame = new WriteAndMakeResultsFrame(
                    fileEngine, sourceList, targetList, lessonName, sourceListName);
            frame.setVisible(true);
            dispose();
        } catch (IllegalArgumentException | IllegalStateException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonStartActionPerformed


    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddChoicejButton;
    private javax.swing.JButton AddjButton;
    private javax.swing.JButton ChoicejButton;
    private javax.swing.JLabel LessonNamejLabel;
    private javax.swing.JTextField LessonNamejTextField;
    private javax.swing.JTextArea SourceListjTextArea;
    private javax.swing.JTextArea TargetListjTextArea;
    private javax.swing.JButton jButtonAddSwitch;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonVerify;
    private javax.swing.JLabel jLabelAddOrChoice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldSourceListName;
    // End of variables declaration//GEN-END:variables
}
