/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUİ;

import DataStructers.MyLinkedList;
import FileProcess.FileEngine;
import javax.swing.JOptionPane;
import java.util.List;
/**
 *
 * @author aliemre
 */
public class WriteAndMakeResultsFrame extends javax.swing.JFrame {

    /**
     * Creates new form WriteAndMakeResultsFrame
     */
    FileEngine fileEngine;
    private String sourceList;
    private String targetList;
    private String lessonName;
    private String sourceListName;

    public WriteAndMakeResultsFrame(
            FileEngine fe, String sourceList, String targetList,
            String lessonName, String sourceListName) {
        initComponents();
         this.sourceList=sourceList;
         this.targetList=targetList;
         this.lessonName=lessonName;
         this.sourceListName=sourceListName;
         fileEngine = fe; 
         writeResults();
         ResultsjTextArea.setEditable(false);
         jLabelLessonOrName.setText("Ders / Numara");
         jRadioButtonLesson.setSelected(true);
         jTextFieldLessonOrName.setText(lessonName);
         
         
       
        
    } 

    private void writeResults() {
        List<MyLinkedList> list = fileEngine.writeResultsOnTextArea(
                sourceList, targetList, lessonName, sourceListName);
        StringBuilder text = new StringBuilder(lessonName + " sonuçları\n\n");
        for (MyLinkedList student : list) {
            if (student.isEmpty()) continue;
            for (int i = 1; i < student.size2(); i++) {
                if (student.getStr1(i).equals(lessonName)) {
                    text.append(student.getStr1(0)).append(" -> ")
                            .append(student.getStr2(0)).append(" -> ")
                            .append(student.getStr2(i)).append('\n');
                }
            }
        }
        ResultsjTextArea.setText(text.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupResultOptions = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultsjTextArea = new javax.swing.JTextArea();
        SavejButton = new javax.swing.JButton();
        ExitjButton = new javax.swing.JButton();
        jRadioButtonLesson = new javax.swing.JRadioButton();
        jRadioButtonStudentInformation = new javax.swing.JRadioButton();
        jRadioButtonAllOfThem = new javax.swing.JRadioButton();
        jTextFieldLessonOrName = new javax.swing.JTextField();
        jLabelLessonOrName = new javax.swing.JLabel();
        jButtonMakeTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        ResultsjTextArea.setColumns(20);
        ResultsjTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultsjTextArea);

        SavejButton.setText("Save");
        SavejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButtonActionPerformed(evt);
            }
        });

        ExitjButton.setText("Exit");
        ExitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjButtonActionPerformed(evt);
            }
        });

        buttonGroupResultOptions.add(jRadioButtonLesson);
        jRadioButtonLesson.setText("For Lesson");
        jRadioButtonLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLessonActionPerformed(evt);
            }
        });

        buttonGroupResultOptions.add(jRadioButtonStudentInformation);
        jRadioButtonStudentInformation.setText("For a Student Number");

        buttonGroupResultOptions.add(jRadioButtonAllOfThem);
        jRadioButtonAllOfThem.setText("For All Information");
        jRadioButtonAllOfThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAllOfThemActionPerformed(evt);
            }
        });

        jLabelLessonOrName.setText("LessonOrName");

        jButtonMakeTxt.setText("Make");
        jButtonMakeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLesson)
                                    .addComponent(jRadioButtonAllOfThem)
                                    .addComponent(jRadioButtonStudentInformation))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelLessonOrName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldLessonOrName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonMakeTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SavejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(ExitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SavejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jRadioButtonLesson)
                .addGap(69, 69, 69)
                .addComponent(jRadioButtonStudentInformation)
                .addGap(72, 72, 72)
                .addComponent(jRadioButtonAllOfThem)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLessonOrName)
                    .addComponent(jTextFieldLessonOrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonMakeTxt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(ExitjButton))
        );

        jRadioButtonAllOfThem.getAccessibleContext().setAccessibleName("For All Information\n(no need write anything)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButtonActionPerformed

        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitjButtonActionPerformed


    private void SavejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejButtonActionPerformed
        try {
            boolean saved = fileEngine.writeSouceListLogs(sourceList, targetList, lessonName, sourceListName);
            JOptionPane.showMessageDialog(this, saved ? "Notlar kaydedildi." : "Notlar kaydedilemedi.");
        } catch (IllegalArgumentException | IllegalStateException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SavejButtonActionPerformed

    private void jRadioButtonLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLessonActionPerformed
            

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLessonActionPerformed

    private void jButtonMakeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeTxtActionPerformed
        String value = jTextFieldLessonOrName.getText().trim();
        boolean created;
        if (jRadioButtonLesson.isSelected()) {
            created = fileEngine.makeTxtLesson(value);
        } else if (jRadioButtonStudentInformation.isSelected()) {
            created = fileEngine.makeTxtStudentNotes(value);
        } else if (jRadioButtonAllOfThem.isSelected()) {
            created = fileEngine.makeTxtAllResults(sourceListName);
        } else {
            JOptionPane.showMessageDialog(this, "Bir çıktı türü seçin.");
            return;
        }
        JOptionPane.showMessageDialog(this, created
                ? "TXT masaüstünde oluşturuldu."
                : "TXT oluşturulamadı. Girdiğiniz ders/numarayı ve dosya yazma iznini kontrol edin.");
    }//GEN-LAST:event_jButtonMakeTxtActionPerformed

    private void jRadioButtonAllOfThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllOfThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAllOfThemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitjButton;
    private javax.swing.JTextArea ResultsjTextArea;
    private javax.swing.JButton SavejButton;
    private javax.swing.ButtonGroup buttonGroupResultOptions;
    private javax.swing.JButton jButtonMakeTxt;
    private javax.swing.JLabel jLabelLessonOrName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAllOfThem;
    private javax.swing.JRadioButton jRadioButtonLesson;
    private javax.swing.JRadioButton jRadioButtonStudentInformation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLessonOrName;
    // End of variables declaration//GEN-END:variables
}
